### ISSUE TITLE
Consider merging `cfr_static()` and `cfr_rolling()`

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#105]
> `cfr_static()` and `cfr_rolling()` source codes are basically the same. We need to plan on merging them (as least internally if we want to keep both exported functions). I am not yet sure which one should fold under the other but it doesn't make sense to keep them separate.

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/cfr/pull/103#discussion_r1392888806_

**Comment by pratikunterwegs** [comment]
This issue is slated for brief exploration with the writing of an internal method `.cfr_static()` without input checks that can be used in `cfr_static()` and `cfr_rolling()`.

**Comment by pratikunterwegs** [comment]
After discussing with @adamkucharski I think this is unlikely to be of much benefit as both functions use `.estimate_severity()` internally. The parts of `cfr_rolling()` that differ from `cfr_static()` are required to produce function specific messages, or to reduce unnecessary computation. This code is pretty much as DRY as it can be (at least without effectively vectorising `cfr_static()`) - alternative suggestions are welcome, but otherwise this issue can probably be closed.

**Comment by adamkucharski** [comment]
Agree, limited value to further work on this I think.
