### ISSUE TITLE
Consider `optim()` in `estimate_severity()`

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#107]
This issue is related to the full package review in #103 and affects the likelihood calculation step.
              
>- why not use `optim`?
>- what happens to diseases with CFR < 1e-3 (i.e. most pathogens)?

A further suggestion is that using `optim()` and `lchoose()` together could remove the need for the `poisson_threshold` and associated method.

_Originally posted by @sbfnk in https://github.com/epiverse-trace/cfr/pull/103#discussion_r1392631865_

**Comment by adamkucharski** [comment]
Do we use the profile likelihood in that calculation to generate CIs? Or is it just to find max likelihood? If so, optim probably better (as long as keep a check on binomial vs Poisson). Otherwise could consider integration with quickfit functionality.

**Comment by pratikunterwegs** [comment]
Thanks, we are using the method to get CIs, so might be good to keep as is? [This SO post suggests](https://stats.stackexchange.com/questions/27033/in-r-given-an-output-from-optim-with-a-hessian-matrix-how-to-calculate-paramet) a way to get CIs from `optim()` output, but unsure how applicable it is. Could be a good task for future releases.

**Comment by adamkucharski** [comment]
Some options were addressed a bit here: https://github.com/epiverse-trace/quickfit/issues/2

But current plan is to keep {quickfit} light and focus on stability for our use cases (e.g. integration with epichains, superspreading, and maybe some simple fitting with epidemics etc.)

**Comment by adamkucharski** [comment]
Suggestion following discussion with @pratikunterwegs:
1. Expand grid search to range from `seq(0,1,1e-4)`, i.e. 0.01% severity increments
2. Calculate simple estimate of ratio of deaths to cases with known outcomes (p_mid) and give warning if below 0.01%
3. Include switch to Poisson or Normal approximation for large N (and check that results are sensible as cross the N=100 and p=0.05 boundary).

Example code for `estimate_severity`:

```
# maximum likelihood estimation for corrected severity
  pprange <- seq(from = 0, to = 1.0, by = 1e-4)

  # Calculate likelihood - use binomial for small samples and Poisson/Normal
  # approximation for larger numbers

  # Direct estimate of p:
  p_mid <- total_deaths/round(u_t * total_cases)
  
  warning("Ratio of total deaths to total cases with known outcome is below 0.01% so estimates may be unreliable")
  
  # Binomial approx
  if(total_cases < poisson_threshold){
    lik_out <- function(total_cases,total_deaths,u_t,pp){
      lchoose(round(u_t * total_cases), total_deaths) +
      (total_deaths * log(pp)) +
      (((u_t * total_cases) - total_deaths) * log(1.0 - pp))
    }
  } 
  
  # Poisson approx
  if((total_cases >= poisson_threshold) & p_mid<0.05){
    lik_out <- function(total_cases,total_deaths,u_t,pp){
      stats::dpois(
        total_deaths, pp * round(u_t * total_cases),
        log = TRUE
      )
    }
    message(paste0(total_cases," total cases and p=", signif(p_mid,3), "so using 
                   Poisson approximation to binomial likelihood"))
  } 
  
  # Normal approx
  if((total_cases >= poisson_threshold) & p_mid>=0.05){
    lik_out <- function(total_cases,total_deaths,u_t,pp){
      stats::dnorm(
        total_deaths, mean = pprange * round(u_t * total_cases), sd = pp * (1-pp) * round(u_t * total_cases),
        log = TRUE
      )
    }
    message(paste0(total_cases," total cases and p=", signif(p_mid,3), "so using 
                   Normal approximation to binomial likelihood"))
  }
  
  
  lik <- lik_out(total_cases,total_deaths,u_t,pprange)
```

**Comment by pratikunterwegs** [comment]
Just tackling this issue - `estimate_severity()` is used in `cfr_rolling()` (with the expanding time window). Should the choice of likelihood function should be made for each day of the data? I'm guessing not, and that it should be chosen based on the total cases and p_mid as in `cfr_static()`?

**Comment by adamkucharski** [comment]
The choice is based on N, D and u_t (i.e. proportion with known outcome) going into the likelihood. So for `cfr_rolling`, I think it should be based on whatever is going in – i.e. if the window is initially quite small, may use binomial, but for longer window, with more cases that have accrued, would switch to an approximation. Otherwise may get odd results if define based on what cases later appear (because may use approximation on early window with too few data points, if I've understood the question correctly)?

**Comment by pratikunterwegs** [comment]
Yes that was my question, thanks! Is it useful to inform users that daily estimates might be from different methods?

**Comment by pratikunterwegs** [comment]
Just to answer a question from Weds as well, `pprange <- seq(from = 0, to = 1.0, by = 1e-4)` gives `Inf` in the Binomial approximation as there's a `log(pp)` operation in there. I'm fairly sure now that that's why the starting value was `1e-3`.

**Comment by adamkucharski** [comment]
Good point – in that case, best to start with non-zero value (e.g. 1e-4)? Are we currently just notifying user with message when switch to an approximate method? If so, that seems fine to keep as-is?

**Comment by pratikunterwegs** [comment]
Yes - that's the fix I'm adopting. No message in `cfr_rolling()` though as that fills the screen.
