### ISSUE TITLE
Test for forward convolution of onsets to generate cases with expected known outcome

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#13]
Any convolution method for known outcomes should produce same vector for 'cases that have known outcome on day X', based on equations 1-4 in [Nishiura et al](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006852).

**Comment by pratikunterwegs** [comment]
Checking whether this is already handled by Tim R's implementation of `known_outcomes()` or whether there's further development required. Is there a call for adding tests that compare the estimates from `known_outcomes()` with 'true' known outcomes?

**Comment by adamkucharski** [comment]
This has now been resolved I think - was mostly about checking the theory vs previous implementation

**Comment by pratikunterwegs** [comment]
Thanks, will close as resolved.
