### ISSUE TITLE
CFR stands for Risk or Ratio?

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/cfr#130]
The reference paper uses "Ratio" and the package documentation uses "Risk". Both terminologies are discussed in the literature.

From [Kelly and Cowling](https://doi.org/10.1097/ede.0b013e318296c2b6), "This conditional probability of mortality among classified cases can be termed the “case fatality risk.” Such a risk is not a rate because time is not part of the denominator. Recognizing this, many authors have preferred the term “case fatality ratio.” However, neither is this quantity strictly a ratio because it is not the comparison of like quantities. Case fatality estimates a conditional probability, and should thus be considered a risk." 

For [Nishiura et al.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006852), "the cCFR is interpreted as the conditional probability of death given confirmed diagnosis". So although Nishiura names the CFR as "Ratio", we can interpret that we are calculating the "Risk". Additionally, the ascertainment ratio analysis used in {cfr} uses the CFR as a "risk ratio", getting the ratio of CFR in group A (observed in data) to that in group B (known for the disease), so it sounds coherent to make this distinction (as defined by [Lipsitch et al.](https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003846#sec005) but for causal interpretations).

However, this also requires the context of the study or data collection. From [Mantha](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30439-4/fulltext), "In the context of the COVID-19 pandemic, case fatality ratios are obtained from cross-sectional studies, whereas risk estimates are obtained from prospective cohort studies". As stated in [Nishiura et al.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006852), {cfr} focuses on the "Calculation of the ratio of the cumulative number of deaths to cases during the course of an epidemic". It is not in the context of cohort studies, but it is closer to a cross-sectional calculation. We have previously named this as [incidence-based analysis](https://github.com/epiverse-trace/cfr/issues/79#issuecomment-1689783720) to differentiate it from the cohort-based or survival-based analysis.

In tutorials, we refer to papers using these two terms. The term "risk" is used by [Yang et al.](https://www.nature.com/articles/s41467-020-19238-2) and [Lipsitch et al.](https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003846#sec005). The term "ratio" is used in [Verity et al.](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext), [Fraser et al.](https://www.science.org/doi/full/10.1126/science.1176062), [Ghani et al.](https://academic.oup.com/aje/article/162/5/479/82647?login=false#620743), [Nishiura et al.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006852). Having an agreement for this issue would be informative to justify the terms used across documentation and to share this as explanation documentation elsewhere to users.

**Comment by adamkucharski** [comment]
I think an argument could be made for using ratio or risk, as long as we're consistent in the accompanying documentation (and training materials). Mathematically, 'ratio' generally means the numerator and denominator have same units (i.e. number of people in the case of a CFR), whereas rate implies different units (it doesn't necessarily have to be with respect to time). As you say, 'risk' usually implies a probability (which is why we calculate odds ratios when we don't have a denominator from a cohort study), and therefore we are interested in getting at the value of the risk when estimating CFR. 'Case fatality rate' is commonly used, but mathematically incorrect, as you note (much like 'secondary attack rate').

**Comment by pratikunterwegs** [comment]
Just as a reminder, we went over this question in the full package review #103 where we shifted to "risk". I'm happy to shift to "ratio" as well if it makes more sense. Naively, risk to me would indicate a prognosis, while ratio suggests a retrospective assessment.

**Comment by avallecam** [comment]
> I think an argument could be made for using ratio or risk, as long as we're consistent in the accompanying documentation (and training materials)

Yes, agree. We are currently moving to use risk for consistency.

> 'risk' usually implies a probability (...) and it is indeed risk P(death | case) we are interesting in when estimating CFR

Yes, this argument is a +1 to keep it as a "risk".

> we went over this question in the full package review #103 where we shifted to "risk"

Thanks for that reference. Actually, is easier to find the commit https://github.com/epiverse-trace/cfr/pull/103/commits/34438c9249b8fcb655837e55f34bf09e64a44ea1 than the resolved conversation, hehe. Is there a way to open all at once?

**Comment by pratikunterwegs** [comment]
Closing this issue as we have standardised on 'risk' over 'ratio'.
