### ISSUE TITLE
Deconvolution vs backwards sampling

### ISSUE THREAD

**Issue by seabbs** [epiverse-trace/cfr#2]
Nice to see this project kicking off. I see that the MVP currently uses backwards sampling which has a range of bias issues. 

Here is some code for a matrix approach to convolution which should generally be more efficient as well as a deterministic deconvolution method that works by solving for the matrix inverse. Note this example is tuned for ONS prevalence as we were aiming to recreate the method they use to get incidence (which they confirmed we had done via email). 

https://gist.github.com/seabbs/fb1bc9c79c3dd7117f9314cb97e71615

(note this comes with no licensing for free reuse etc without attribution).

**Comment by adamkucharski** [comment]
Good point - a simple time shift based on mean delay would probably be a better placeholder.

I explored matrix inversion approaches to deconvolution a bit early in the pandemic, but hit issues with singular convolution matrices (which will happen when delay is away from the diagonal - as you also flag in that gist). Managed to get some estimates out with alternative numeric approaches (e.g. Moore-Penrose psuedoinverse), but not ideal to have poorly characterised stability/accuracy.

![Deconvolution using pseudoinverse](https://user-images.githubusercontent.com/8329046/174997837-d6bff2ea-86cc-4cde-82ed-6cafa322aa3c.png)

There are also packages like incidental, but deconvolution method can be quite slow, and I haven’t properly explored how well they deal with edge cases.

**Comment by seabbs** [comment]
Yup agree on issues with singular convolution matrices. Most of the E-M and spline-based approaches I've seen haven't worked very well on real-world data. 

A lot of the complexity goes away if you don't need a real-time model as then a mean shift prior and a GP on the residuals works well and is fast (like 20 seconds with full MCMC <1 using TMB). Having a generative process helps a lot if real-time estimates are a concern.

**Comment by pratikunterwegs** [comment]
Closing this issue as superseded by [this PR in {EpiNow2}](https://github.com/epiforecasts/EpiNow2/pull/545) which will then move to the {howto} repo.
