### ISSUE TITLE
Add vignette describing user options

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#4]
There are a few user options that are likely to be useful for estimation/comparison:
- Fixed CFR (i.e. 'total deaths'/'total expected cases with known outcome') vs time-varying CFR (i.e. 'deaths on day X'/'expected cases with known outcome on day X')

- Whole timeseries (i.e. 'total deaths'/'expected cases with known outcome') vs expanding window (i.e. 'total deaths up to day X'/'total expected cases with known outcome up to day X')

- Small numbers of events (e.g. Ebola 1976) vs large numbers of events (e.g. COVID)

- Raw vs smoothed timeseries (i.e. effectively implementing an observation model if reporting cyclical or noisy). Possibly something to implement in a separate package, as useful across package?

- Efficiency (e.g. parallelisation) across countries/time periods

**Comment by thimotei** [comment]
Would also be useful to add an example with a linelist, converting it to a timeseries using `incidence2`. See also issue #7

**Comment by adamkucharski** [comment]
Perhaps clearer terminology for expanding window vs time-varying CFR (e.g. in x-axes) would be 'CFR on day X' vs 'CFR up to day X'

**Comment by pratikunterwegs** [comment]
Just checking whether this issue is still relevant, and if so how it might relate to the current contents of the vignettes? If I could get some pointers I can go ahead and make changes.

**Comment by adamkucharski** [comment]
The case study document @CarmenTamayo is working on should cover a lot of this - can then decide where content sits best among vignette/training/blog (as it also touches on wider issues about what 'ground truth' should be when evaluating different methods)

**Comment by pratikunterwegs** [comment]
Thanks - happy to integrate that as it comes up. I think we do have some documentation in the vignettes for small vs big outbreaks and the different methods. I think @avallecam is also going to take a look, so perhaps more focused issues would be better than adding a full vignette?

**Comment by pratikunterwegs** [comment]
Closing this as stale - seems focus for this has moved to case studies repo, happy to help there.
