### ISSUE TITLE
Standardise data formatting

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#5]
If implementing and comparing different methods for estimation, need to ensure input and output data formats consistent, e.g. vectors of dates, cases and deaths. Tests also needed to check correct format (e.g. for date and numeric vector)

**Comment by pratikunterwegs** [comment]
Thanks - currently, all estimation functions take, iirc, a dataframe of cases, deaths, and known outcomes, and return a data.frame of severity estimates and estimate limits. `known_outcomes()` is slightly different - but perhaps should be an internal function.

Will work on looking into {incidence2} and what the data formats there are.

**Comment by adamkucharski** [comment]
Sounds good – this issue will likely come up in other Epiverse packages too, so would be nice to have a consistent approach.

`known_outcomes()` can be useful as a standalone function (e.g. if user has timeseries of cases, but only total deaths – @CarmenTamayo has been putting together some use cases based on this)

**Comment by pratikunterwegs** [comment]
Thanks - I'm currently pitching a `prepare_data()` generic and method for `<incidence2>` objects over on issue #39 .

**Comment by pratikunterwegs** [comment]
Closing as resolved by discussions around the input and output format; converged on inputs as a three column data.frame of date, cases, and deaths, and a data.frame output appropriate to the severity measure.
