### ISSUE TITLE
Grouping for <incidence2> objects

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#52]
This issue is about how the `prepare_data()` for `<incidence2>` objects treats grouped objects.

The current behaviour is to error when grouped `<incidence2>` objects are passed, and to advise users to call `incidence2::regroup()` on the object before passing it.

Alternatives include respecting the grouping structure, but this could require taking on a data science repository such as {data.table} or {dplyr} + {tidyr}, although base-R only options could also be implemented.

> Can we open another issue for the incidence2 grouping discussion please to make sure this stays on our radar? I think it's an important point.

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/datadelay/issues/39#issuecomment-1602460696_

**Comment by pratikunterwegs** [comment]
Could I get opinions on the preferred way to resolve this issue? Happy to implement a method that respects grouping - any preferences on how this should be done?

**Comment by adamkucharski** [comment]
Am I correct that the core question is how to transform a line list into a 3 column data.frame (date, new cases, new deaths) via incidence2 (which treats cases/deaths as groups)? Expect this issue will come up elsewhere too, e.g. when we want to input two linked timeseries in EpiNow2 (cc @jamesmbaazam and @sbfnk)?

**Comment by pratikunterwegs** [comment]
We're taking `<incidence2>` objects as the starting point. The issue there is that when these objects are grouped, aggregating them to `date, cases, deaths` using {incidence2} leads to NAs when not all groups have incidence reported for a specific date. {cfr} cannot deal with these `NA`s.

How should {cfr} deal with this case? Should we tell users to split their `<incidence2>` object into a list by group, and apply cfr functions over the list? Or should we aggregate the incidences internally, treating `NA` for any group as zero? Or should we keep the current implementation and error on grouped data?

**Comment by adamkucharski** [comment]
So sounds like it's a matter of how we want to deal with missing data, i.e. is it a zero count or just unknown entry? Looks like `prepare_data()` already has option to replace `NA` with 0s if its the first of these options? Possible to just apply same rule to grouped data if user selects this option?

**Comment by pratikunterwegs** [comment]
That would mean replacing NA with 0, and then aggregating the data by date - so removing the groups. I can implement this if that's the preferred solution. @Bisaloo initially made the comment - would this be acceptable?

**Comment by Bisaloo** [comment]
Isn't the issue of `NA` when aggregating exactly the same whether we have groups or not? I would follow @adamkucharski's suggestion and apply the same fix as on non-grouped data.

This doesn't mean if have to drop groups though. You can aggregate data by groups.

Said differently, the preferred option IMO would be:

> Should we tell users to split their <incidence2> object into a list by group, and apply cfr functions over the list?

But done internally. The same way that tidyverse users calling `group_by()`, and then `mutate()` or `summarise()` don't have to worry about writing the loop themselves.

cc @TimTaylor

**Comment by pratikunterwegs** [comment]
Pushing this issue into focus again as it's a good time to implement a fix - @TimTaylor would you like to come in on this?

If there's consensus, I'll implement the suggestion of splitting objects by group, preparing them separately, and returning a single data.frame. The grouping variables would be added as columns, which allows the data to be passed to `dplyr::group_by()` or `tidyr::nest()`.

**Comment by pratikunterwegs** [comment]
Thanks - I'll take this route while trying to avoid dependencies.

**Comment by pratikunterwegs** [comment]
We have incidence2 in Suggests only - would that still give me data.table? I somehow think it would complain.

**Comment by pratikunterwegs** [comment]
Okay thanks - let me see which is the most workable option. I still feel that users should deal with their grouped data structures manually so that they have full oversight of their pipelines. It's pretty easy to apply cfr functions over nested or grouped data as well, as we show in a vignette.

**Comment by pratikunterwegs** [comment]
My mistake - this issue does need fixing, as we can't assume that users can use a split/apply/combine workflow for their data. We do show how to do it, but it's on us to make it easier.

**Comment by pratikunterwegs** [comment]
Thanks for coding up the solution @TimTaylor - I'll probably go with the second option to avoid taking on {dplyr} and {tidyr}.
