### ISSUE TITLE
Allow tracking pkgdown/

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#56]
This issue is to flag that we may want to add the `pkgdown/` directory to tracking in the future.

> This folder can contain important files we want to commit. Do you have any issues that lead you to add it here?

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/cfr/pull/54#discussion_r1262243657_

**Comment by pratikunterwegs** [comment]
The example contains mostly the pkgdown YAML, which we already include in our top-level directory (across packages, based on {packagetemplate}) - does the locations of this file also need to be changed?

**Comment by Bisaloo** [comment]
Both locations are valid so no need to change it
