### ISSUE TITLE
Uncertainty in time-varying CFR estimate

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#6]
Currently [cfr_calculation.R](https://github.com/epiverse-trace/datadelay/blob/main/R/cfr_calculation.R) only calculates the expected value of CFR over time. Need to implement uncertainty for this (or deprecate the function if another is later decided to be preferable for main implementation).

**Comment by pratikunterwegs** [comment]
Is this issue fixed by the current implementation of `estimate_time_varying()` from #23? Could be closed if so.

**Comment by adamkucharski** [comment]
Yep, we've now got binomial uncertainty in that function
