### ISSUE TITLE
Comparison with other methods

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#7]
In vignette, would be useful to show comparisons with estimation in [EpiNow2](https://epiforecasts.io/EpiNow2/reference/estimate_secondary.html) and [coarseDataTools](https://cran.r-project.org/web/packages/coarseDataTools/vignettes/CFR_vignette.html), noting any differences in required data (e.g. cases & deaths vs recoveries & deaths). Could also build comparisons into `episoap` template for CFR estimation, along with calls to `epiparameter` and other relevant packages.

**Comment by adamkucharski** [comment]
Script comparing timeseries estimation with fixed CFR and estimation based on known outcomes in linelist, using global.health 2022 data as example: [https://github.com/adamkucharski/ebola-cfr/blob/main/scripts/script_2022.R](https://github.com/adamkucharski/ebola-cfr/blob/main/scripts/script_2022.R)

**Comment by adamkucharski** [comment]
In terms of adjusting for truncation, estimating CFR based only on cases in linelist with known outcomes should produce an unbiased estimate if the delay from onset-to-outcome is the same for fatal and non-fatal outcomes (because we are calculating the ratio of two variables sampled from the early part of the two same distributions).

**Comment by adamkucharski** [comment]
For coarseDataTools, `EMforCFR()` might be a useful starting point for comparison with Ebola data.

**Comment by pratikunterwegs** [comment]
Closing as this is now covered conceptually in the Readme.
