### ISSUE TITLE
activate alert boxes in static_severity vignette

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/cfr#70]
In [estimate_static_severity vignette](https://epiverse-trace.github.io/cfr/articles/estimate_static_severity.html#use-case), sth is happening with the alert boxes for: 
- use case 
- what we have
- concept...

This is how it looks to me:
![image](https://github.com/epiverse-trace/cfr/assets/21230390/472f98f1-dffa-4002-a73f-11ca0b42b598)

I think the expected look is like in [estimate_time_varying_severity vignette](https://epiverse-trace.github.io/cfr/articles/estimate_time_varying_severity.html#use-case):
![image](https://github.com/epiverse-trace/cfr/assets/21230390/de988262-626b-40e2-9338-3b7bdca897c6)

**Comment by pratikunterwegs** [comment]
Thanks for pointing this out - I also noticed this but thought that it might be an issue wit rendering locally on my system. I'm not sure what causes the highlighting to not show, but I will try and figure it out.
