### ISSUE TITLE
Estimation of under-ascertained cases from deaths

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/cfr#9]
Add functionality that can estimate cases from reported deaths and a known CFR. Starting point could be the estimator in `scale_cfr` function (as was done in early version of CMMID COVID reports). Follow-up functionality could account for varying reporting over time, as implemented by [Russell et al, 2020](https://github.com/thimotei/CFR_calculation) – might be useful to compare with similar functionality in packages like `EpiNow2` and `coarseDataTools`, if such methods are available, and data formats are same (e.g. cases & deaths over time).

**Comment by pratikunterwegs** [comment]
Hi @adamkucharski would you say this issue is resolved by the function `estimate_reporting()`? I'll close this issue if so.

**Comment by pratikunterwegs** [comment]
Closing this as fixed by #23
