### ISSUE TITLE
Different return values across `cfr_*()` functions

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/cfr#95]
Currently, the `cfr_time_varying()` & `cfr_rolling()` functions return different objects. Because of their similarity in names & signatures, one could expect the same return format.

``` r
library(cfr)

data("ebola1976")

cfr_time_varying(
  ebola1976
) |> 
  head()
#>         date cases deaths severity_mean severity_low severity_high
#> 1 1976-08-25     1      0            NA           NA            NA
#> 2 1976-08-26     0      0            NA           NA            NA
#> 3 1976-08-27     0      0            NA           NA            NA
#> 4 1976-08-28     0      0            NA           NA            NA
#> 5 1976-08-29     0      0            NA           NA            NA
#> 6 1976-08-30     0      0            NA           NA            NA

cfr_rolling(
  ebola1976
) |> 
  head()
#>   severity_mean severity_low severity_high
#> 1             0            0         0.975
#> 2             0            0         0.975
#> 3             0            0         0.975
#> 4             0            0         0.975
#> 5             0            0         0.975
#> 6             0            0         0.975
```

<sup>Created on 2023-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Am I missing a technical or statistical reason why `cfr_time_varying()` returns the input data with extra columns, while `cfr_rolling()` only returns the new columns?

**Comment by pratikunterwegs** [comment]
Thanks, no, there's no reason - I can push a fix where both return only the date and the estimates. I don't think cases and deaths should be in there, but the including the date makes plotting easier.
